### PR TITLE
catkin build support

### PR DESCRIPTION
**Pull request by akshitj1**
Hi @kthohr , I am using this library for some ROS package and catkin build system is very common in ROS community. I have required changes for catkin support. Will these be relevant to original repo? I can make further changes if you want.

### CODE REVIEW

**Comment by conradsnicta** [comment]
@akshitj1 - Not sure if Keith is still developing / maintaining optimlib. There's another optimisation library based on Armadillo that's actively developed: [ensmallen](https://github.com/mlpack/ensmallen)
* https://github.com/mlpack/ensmallen
* http://ensmallen.org/

**Comment by akshitj1** [comment]
Hi @conradsnicta , Thanks for the recommendation. I took a look at mentioned repo, But it seems that it does not contains Nelder-Mead algorithm for which I had used this library. I don't know if switching is possible yet.

**Comment by conradsnicta** [comment]
@akshitj1 It should be relatively easy to port the Nelder-Mead implementation from OptimLib to ensmallen. Maybe submit a pull request at the ensmallen repo. The developers are responsive and can help out.

**Comment by kthohr** [comment]
Not something I'm looking to include at this time. The next version will have Armadillo as an optional dependency.

**Pull request closed without merging**
